---
env:
  global:
    - CC_TEST_REPORTER_ID=64634aec08aacb7cba69b6eb1f4c814228cffe9d167dcb208dcc6d49a4c5c493
sudo: false
language: ruby
cache: bundler
notifications:
  email: false
rvm:
  - 2.5.3
env:
  - BUNDLE_PATH=vendor/bundle
addons:
  postgresql: "9.5"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - gem install bundler -v 2.0.1 --install-dir $BUNDLE_PATH
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec appraisal install --jobs=3 --retry=3
script:
  - bundle exec appraisal rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./coverage
  keep_history: true
  on:
    branch: master
