name: RSpec
on: [push]

jobs:
  services:
    name: Test services
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
        env:
          NGINX_PORT: 80
    steps:
    - curl -v localhost:80 || true
    - curl -v nginx:80 || true
    - curl -v 127.0.0.1 || true

  artifact:
    name: Artifact upload?
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: path/to/artifact

  rspec:
    name: Greeting
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.10
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: arel_toolkit_test
          POSTGRES_USER: postgres
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Test with RSpec
      run: |
        sudo apt-get install -y libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec appraisal install
        bundle exec rake clean
        bundle exec rake compile
        bundle exec appraisal rspec
